<h2>Créer un nouvel utilisateur :</h2>

<form action="index.php" method="post">
    <fieldset>
        <label for="new-user-email">Email</label>
        <input type="email" name="email" id="new-user-email" placeholder="Entrez votre adresse email"/>
    </fieldset>
    <fieldset>
        <label for="new-user-username">Nom d'utilisateur</label>
        <input type="texte" name="username" id="new-user-username" placeholder="Entrez votre nom d'utilisateur"/>
    </fieldset>
    <fieldset>
        <label for="new-user-password">Mot de passe</label>
        <input type="password" name="password" id="new-user-password" placeholder="Entrez votre mot de passe"/>
    </fieldset>
    <fieldset>
        <label for="new-user-confirmPassword">Confirmer le mot de passe</label>
        <input type="password" name="confirmPassword" id="new-user-confirmPassword" placeholder="Confirmez votre mot de passe"/>
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" id=""/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Connexion" id="connect-btn"/>
    </fieldset>
</form>
