<h2>Éditer un utilisateur :</h2>

<form action="index.php" method="post">
    <fieldset>
        <label for="edit-user-email">Email</label>
        <input type="email" name="editEmail" id="edit-user-email" placeholder="Entrez la nouvelle adresse email"/>
    </fieldset>
    <fieldset>
        <label for="edit-user-username">Nom d'utilisateur</label>
        <input type="texte" name="editUsername" id="edit-user-username" placeholder="Entrez le nouveau nom d'utilisateur"/>
    </fieldset>
    <fieldset>
        <label for="edit-user-password">Mot de passe</label>
        <input type="password" name="editPassword" id="edit-user-password" placeholder="Entrez le nouveau mot de passe"/>
    </fieldset>
    <fieldset>
        <label for="edit-user-confirmPassword">Confirmer le mot de passe</label>
        <input type="password" name="editConfirmPassword" id="edit-user-confirmPassword" placeholder="Confirmez le nouveau mot de passe"/>
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" id=""/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Connexion" id="connect-btn"/>
    </fieldset>
</form>
